#!/bin/bash
echo config_1.0_model ; adb push --sync /root/workspace/UnifiedModelBenchmark/tmp/onnx_models/config_1.0_model.onnx /data/local/tmp/hcp/models ; adb -s 3a9c4f5 shell "export LD_LIBRARY_PATH=/data/local/tmp/hcp/libs ; ./data/local/tmp/hcp/ort_benchmark --model=/data/local/tmp/hcp/models/config_1.0_model.onnx --backend=arm --num_warmup=10 --num_runs=40 --num_threads=4 --enable_op_profiling=true --prefix=/data/local/tmp/hcp/config_1.0_model" > config_1.0_model.txt 2>&1 ; 
echo config_0.9_model ; adb push --sync /root/workspace/UnifiedModelBenchmark/tmp/onnx_models/config_0.9_model.onnx /data/local/tmp/hcp/models ; adb -s 3a9c4f5 shell "export LD_LIBRARY_PATH=/data/local/tmp/hcp/libs ; ./data/local/tmp/hcp/ort_benchmark --model=/data/local/tmp/hcp/models/config_0.9_model.onnx --backend=arm --num_warmup=10 --num_runs=40 --num_threads=4 --enable_op_profiling=true --prefix=/data/local/tmp/hcp/config_0.9_model" > config_0.9_model.txt 2>&1 ; 
echo config_0.8_model ; adb push --sync /root/workspace/UnifiedModelBenchmark/tmp/onnx_models/config_0.8_model.onnx /data/local/tmp/hcp/models ; adb -s 3a9c4f5 shell "export LD_LIBRARY_PATH=/data/local/tmp/hcp/libs ; ./data/local/tmp/hcp/ort_benchmark --model=/data/local/tmp/hcp/models/config_0.8_model.onnx --backend=arm --num_warmup=10 --num_runs=40 --num_threads=4 --enable_op_profiling=true --prefix=/data/local/tmp/hcp/config_0.8_model" > config_0.8_model.txt 2>&1 ; 
echo config_0.6_model ; adb push --sync /root/workspace/UnifiedModelBenchmark/tmp/onnx_models/config_0.6_model.onnx /data/local/tmp/hcp/models ; adb -s 3a9c4f5 shell "export LD_LIBRARY_PATH=/data/local/tmp/hcp/libs ; ./data/local/tmp/hcp/ort_benchmark --model=/data/local/tmp/hcp/models/config_0.6_model.onnx --backend=arm --num_warmup=10 --num_runs=40 --num_threads=4 --enable_op_profiling=true --prefix=/data/local/tmp/hcp/config_0.6_model" > config_0.6_model.txt 2>&1 ; 
echo config_0.4_model ; adb push --sync /root/workspace/UnifiedModelBenchmark/tmp/onnx_models/config_0.4_model.onnx /data/local/tmp/hcp/models ; adb -s 3a9c4f5 shell "export LD_LIBRARY_PATH=/data/local/tmp/hcp/libs ; ./data/local/tmp/hcp/ort_benchmark --model=/data/local/tmp/hcp/models/config_0.4_model.onnx --backend=arm --num_warmup=10 --num_runs=40 --num_threads=4 --enable_op_profiling=true --prefix=/data/local/tmp/hcp/config_0.4_model" > config_0.4_model.txt 2>&1 ; 
echo config_0.3_model ; adb push --sync /root/workspace/UnifiedModelBenchmark/tmp/onnx_models/config_0.3_model.onnx /data/local/tmp/hcp/models ; adb -s 3a9c4f5 shell "export LD_LIBRARY_PATH=/data/local/tmp/hcp/libs ; ./data/local/tmp/hcp/ort_benchmark --model=/data/local/tmp/hcp/models/config_0.3_model.onnx --backend=arm --num_warmup=10 --num_runs=40 --num_threads=4 --enable_op_profiling=true --prefix=/data/local/tmp/hcp/config_0.3_model" > config_0.3_model.txt 2>&1 ; 
echo config_0.7_model ; adb push --sync /root/workspace/UnifiedModelBenchmark/tmp/onnx_models/config_0.7_model.onnx /data/local/tmp/hcp/models ; adb -s 3a9c4f5 shell "export LD_LIBRARY_PATH=/data/local/tmp/hcp/libs ; ./data/local/tmp/hcp/ort_benchmark --model=/data/local/tmp/hcp/models/config_0.7_model.onnx --backend=arm --num_warmup=10 --num_runs=40 --num_threads=4 --enable_op_profiling=true --prefix=/data/local/tmp/hcp/config_0.7_model" > config_0.7_model.txt 2>&1 ; 
echo config_0.1_model ; adb push --sync /root/workspace/UnifiedModelBenchmark/tmp/onnx_models/config_0.1_model.onnx /data/local/tmp/hcp/models ; adb -s 3a9c4f5 shell "export LD_LIBRARY_PATH=/data/local/tmp/hcp/libs ; ./data/local/tmp/hcp/ort_benchmark --model=/data/local/tmp/hcp/models/config_0.1_model.onnx --backend=arm --num_warmup=10 --num_runs=40 --num_threads=4 --enable_op_profiling=true --prefix=/data/local/tmp/hcp/config_0.1_model" > config_0.1_model.txt 2>&1 ; 
echo config_0.2_model ; adb push --sync /root/workspace/UnifiedModelBenchmark/tmp/onnx_models/config_0.2_model.onnx /data/local/tmp/hcp/models ; adb -s 3a9c4f5 shell "export LD_LIBRARY_PATH=/data/local/tmp/hcp/libs ; ./data/local/tmp/hcp/ort_benchmark --model=/data/local/tmp/hcp/models/config_0.2_model.onnx --backend=arm --num_warmup=10 --num_runs=40 --num_threads=4 --enable_op_profiling=true --prefix=/data/local/tmp/hcp/config_0.2_model" > config_0.2_model.txt 2>&1 ; 
echo config_0.5_model ; adb push --sync /root/workspace/UnifiedModelBenchmark/tmp/onnx_models/config_0.5_model.onnx /data/local/tmp/hcp/models ; adb -s 3a9c4f5 shell "export LD_LIBRARY_PATH=/data/local/tmp/hcp/libs ; ./data/local/tmp/hcp/ort_benchmark --model=/data/local/tmp/hcp/models/config_0.5_model.onnx --backend=arm --num_warmup=10 --num_runs=40 --num_threads=4 --enable_op_profiling=true --prefix=/data/local/tmp/hcp/config_0.5_model" > config_0.5_model.txt 2>&1 ; 